name: Publish gh-pages

on:
  push:
    branches: [ publish ]

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    # Checks-out the repository 
    - uses: actions/checkout@v2
      
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: 3.8
        activate-environment: sphinx-doc
        environment-file: environment.yml    
    
    - name: Build docs
      shell: bash -l {0}
      run: |
        make clean
        make html
        
    - name: Commit documentation changes
      run: |
        export REPO_PATH=$(pwd)
        cd /tmp/
        git clone https://github.com/openteamsinc/openteams-scrud-strategy.git --branch=gh-pages gh-pages
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        cp -R ${REPO_PATH}/build/html/* docs/
        touch .nojekyll
        git add .nojekyll
        git add .
        git commit -m "Update documentation" -a || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        force: True
        directory: /tmp/gh-pages/docs
        github_token: ${{ secrets.SEMANTIC_HTTP_SPEC_KEY }}